#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FonsecaDB")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPrecoCombustivei(PrecoCombustivei instance);
    partial void UpdatePrecoCombustivei(PrecoCombustivei instance);
    partial void DeletePrecoCombustivei(PrecoCombustivei instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FonsecaDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PrecoCombustivei> PrecoCombustiveis
		{
			get
			{
				return this.GetTable<PrecoCombustivei>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PrecoCombustiveis")]
	public partial class PrecoCombustivei : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nomePais;
		
		private string _precoGasolina;
		
		private string _precoGasoleo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnomePaisChanging(string value);
    partial void OnnomePaisChanged();
    partial void OnprecoGasolinaChanging(string value);
    partial void OnprecoGasolinaChanged();
    partial void OnprecoGasoleoChanging(string value);
    partial void OnprecoGasoleoChanged();
    #endregion
		
		public PrecoCombustivei()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomePais", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nomePais
		{
			get
			{
				return this._nomePais;
			}
			set
			{
				if ((this._nomePais != value))
				{
					this.OnnomePaisChanging(value);
					this.SendPropertyChanging();
					this._nomePais = value;
					this.SendPropertyChanged("nomePais");
					this.OnnomePaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precoGasolina", DbType="VarChar(10)")]
		public string precoGasolina
		{
			get
			{
				return this._precoGasolina;
			}
			set
			{
				if ((this._precoGasolina != value))
				{
					this.OnprecoGasolinaChanging(value);
					this.SendPropertyChanging();
					this._precoGasolina = value;
					this.SendPropertyChanged("precoGasolina");
					this.OnprecoGasolinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precoGasoleo", DbType="VarChar(10)")]
		public string precoGasoleo
		{
			get
			{
				return this._precoGasoleo;
			}
			set
			{
				if ((this._precoGasoleo != value))
				{
					this.OnprecoGasoleoChanging(value);
					this.SendPropertyChanging();
					this._precoGasoleo = value;
					this.SendPropertyChanged("precoGasoleo");
					this.OnprecoGasoleoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
