<?xml version="1.0" encoding="utf-8"?><Database Name="FonsecaDB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=FonsecaDB.mssql.somee.com;Initial Catalog=FonsecaDB;User ID=pfonseca95_SQLLogin_1;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FonsecaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PrecoCombustiveis" Member="PrecoCombustiveis">
    <Type Name="PrecoCombustivei">
      <Column Name="nomePais" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="precoGasolina" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="precoGasoleo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>